copyright: Copyright &copy; 2020-2024 OS4D ltd.
dev_addr: 127.0.0.1:8001
docs_dir: docs/src
edit_uri: 'blob/develop/docs/'
repo_url: https://github.com/os4d/birder
site_author: OS4D
site_description: ""
site_dir: ./~build/docs
site_name: Birder
site_url: https://github.com/os4d/birder
strict: false
exclude_docs: |
  _docs/*
  _hooks/*
  _includes/*
  _scripts/*
  ~*

markdown_extensions:
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: '.'
      check_paths: true

theme:
  name: "material"
  color_mode: auto
  custom_dir: docs/_theme/overrides
  favicon: img/favicon.ico
  logo: img/logo.png
#  highlightjs: true
  hljs_languages:
    - yaml
    - django
  user_color_mode_toggle: true
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohidex
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  extra:
    version:
      provider: mike
      alias: true

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: light blue
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - mkdocstrings:
      default_handler: python
  - awesome-pages
  - search
  - include-markdown:
      encoding: ascii
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: false
      rewrite_relative_urls: true
      heading_offset: 0
      recursive: true

nav:
  - Home: index.md
  - Checks:
      - AMQP: checks/amqp.md
      - Celery: checks/celery.md
      - ElasticSearch: checks/elastic_search.md
      - FTP: checks/ftp.md
      - HTTP: checks/http.md
      - JSON: checks/json.md
      - LDAP: checks/ldap.md
      - Memcache: checks/memcache.md
      - MySQL: checks/mysql.md
      - Passive: checks/passive.md
      - PostgreSQL: checks/pg.md
      - Redis: checks/redis.md
      - S3: checks/s3.md
      - SMTP: checks/smtp.md
      - SSH: checks/ssh.md
      - TCP: checks/tcp.md
      - XML: checks/xml.md
  - Checks: checks.md
  - Docker: docker.md
  - Environment Variables: environment_variables.md
  - Contributing: contributing.md
  - Security: security.md
  - License: license.md

watch:
  - src/

hooks:
  - docs/_hooks/hooks.py
