copyright: Copyright &copy; 2020-2024 OS4D ltd.
dev_addr: 127.0.0.1:8001
docs_dir: docs/src
edit_uri: 'blob/develop/docs/'
repo_url: https://github.com/os4d/birder
site_author: OS4D
site_description: ""
site_dir: ./~build/docs
site_name: Birder
site_url: https://github.com/os4d/birder
strict: false
exclude_docs: |
  _docs/*
  _hooks/*
  _includes/*
  _scripts/*
  ~*

markdown_extensions:
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: "material"
  color_mode: auto
  custom_dir: docs/_theme/overrides
  favicon: img/favicon.ico
  logo: img/logo.png
#  highlightjs: true
  hljs_languages:
    - yaml
    - django
  user_color_mode_toggle: true
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohidex
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
  extra:
    version:
      provider: mike
      alias: true

plugins:
  - mkdocstrings:
      default_handler: python
  - awesome-pages
  - search
#  - gen-files:
#      scripts:
#        - docs/_scripts/get_settings.py
watch:
  - src/

hooks:
  - docs/_hooks/hooks.py
