[mypy]
files = src/birder
mypy_path = $MYPY_CONFIG_FILE_DIR/mypy_tools/:$MYPY_CONFIG_FILE_DIR/src/:
python_version = 3.12
exclude = (?x)(
    ~.*
    | src/dbtemplates.*
  )
plugins = mypy_django_plugin.main,
          mypy_drf_plugin.main

allow_redefinition = true
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
no_implicit_optional = true
strict_equality = true
strict_optional = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[mypy.plugins.django-stubs]
django_settings_module = "birder.config.settings"

[mypy-birder.*]
allow_redefinition = false
check_untyped_defs = false
disallow_any_generics = false
disallow_incomplete_defs = false
disallow_subclassing_any = false
disallow_untyped_decorators = false
disallow_untyped_defs = false
no_implicit_optional = false
strict_equality = false
strict_optional = false

[mypy-birder.admin.*]
ignore_errors = true

[mypy-birder.checks.*]
ignore_errors = true

[mypy-birder.cli.*]
ignore_errors = true

[mypy-birder.management.*]
ignore_errors = true

[mypy-birder.migrations.*]
ignore_errors = true

[mypy-birder.utils.*]
ignore_errors = true

[mypy-birder.views.*]
ignore_errors = true

#### E temporary disabled birder checks

[mypy-bitarray.*]
ignore_missing_imports = True

[mypy-channels.*]
ignore_missing_imports = True

[mypy-constance.*]
ignore_missing_imports = True

[mypy-dramatiq_crontab.*]
ignore_missing_imports = True

[mypy-encrypted_fields.*]
ignore_missing_imports = True

[mypy-environ.*]
ignore_missing_imports = True

[mypy-durations_nlp.*]
ignore_missing_imports = True

[mypy-flags.*]
ignore_missing_imports = True

[mypy-recurrence.*]
ignore_missing_imports = True

[mypy-social_django.*]
ignore_missing_imports = True

[mypy-strategy_field.*]
ignore_missing_imports = True

[mypy-timezone_field.*]
ignore_missing_imports = True

[mypy-unfold.*]
ignore_missing_imports = True
