[tool.poetry]
name = "birder"
version = "1.0.2"
description = ""
authors = ["sax <s.apostolico@gmail.com>"]

[tool.poetry.scripts]
birder = "birder.monitor.cli:main"


[tool.poetry.dependencies]
python = "^3.8"
celery = "*"
circus = "*"
click = "*"
colour = "*"
eventlet = "*"
flask = "*"
flask-bootstrap4 = "*"
flask-caching = "*"
flask-cors = "*"
flask-session = "*"
gunicorn = "*"
psycopg2-binary = "*"
pymysql = "*"
python-slugify = "*"
pytz = "*"
redis = "*"
redis-timeseries = "*"
requests = "*"
attrs = "*"
pyparsing = "^2.4.7"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.3"
isort = "^5.5.4"
pytest = "^6.1.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
