[pytest]
norecursedirs = data .tox _plugin_template ~*
django_find_project = false
addopts =
        --tb=short
        --capture=sys
        --cov birder
        --cov-config=tests/.coveragerc
        --cov-report html
        --dist loadgroup

python_files=test_*.py
markers =
    selenium
    smoke
    skip_models
    skip_buttons
    admin
    integration

asyncio_default_fixture_loop_scope = function

filterwarnings =
    ignore::DeprecationWarning:channels_redis.core
;    ignore::DeprecationWarning:factory.django
;    ignore::DeprecationWarning:pyasn1.codec.ber
;    ignore::UserWarning:pytest_celery.vendors.worker.defaults
;    ignore::django.utils.deprecation.RemovedInDjango60Warning
