services:
  redis:
    image: "redis:alpine"
    ports:
      - "26379:6379"

  memcached:
    image: "memcached:alpine3.21"
    ports:
      - "21121:11211"

  http:
    image: "kennethreitz/httpbin"
    ports:
      - "28000:80"

  ftp:
    image: "delfer/alpine-ftp-server"
    ports:
      - "2221:21"
      - "21000-21010:21000-21010"
    environment:
      ADDRESS: "localhost"

  mariadb:
    image: "bitnami/mariadb"
    ports:
      - "23306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password

  ssh:
    image: "ddev/test-ssh-server:v1.22.2"
    ports:
      - "2222:22"
    environment:
      USERS: "user|password"
      ADDRESS: localhost

  postgres:
    image: "postgres:alpine"
    ports:
      - "25432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD=trust: 1
      POSTGRES_PASSWORD: pwd

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "25672:5672"
      - "21567:15672"
