# Generated by Django 5.2.2 on 2025-07-02 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("birder", "0008_alter_monitor_options_deadline_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": (("can_access_console", "Can Access Console"),)},
        ),
        migrations.AlterField(
            model_name="monitor",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="monitors", to="birder.project"
            ),
        ),
    ]
